name: Build and deploy project

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Generate 200.html
        run: cp build/index.html build/200.html
      - name: Deploy project
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'cool-react-store.surge.sh'
          project: 'build'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
